<div class="modal inmodal modal-fullscreen fade" id="album_content_modal" tabindex="-1" role="dialog" aria-hidden="true" style="height:100%; display: none;">
    <div class="modal-dialog">
        <div class="modal-content animated fadeIn" style="min-height:100%;">
            <div class="modal-header">
                <h2 id="modal_reward_main_title">Select Content</h2>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-2">
                        <h2><i class="fa fa-filter"></i> Filter Content</h2>
                        <div id="new_album_filter_holder"></div>
                    </div>
                    <div class="col-lg-10">
                        <h2><i class="fa fa-image"></i> Available Content</h2>
                        <div id="new_album_content_holder"></div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                <button id="btn_select_content" type="button" class="btn btn-danger"><i class="fa fa-plus"></i> Select content</button>
            </div>
        </div>
    </div>
</div>