<div class="row">
    <div class="col-lg-8 col-lg-offset-2">

        <div class="row">
            <div class="col-lg-2 col-md-2"></div>
            <div class="col-lg-8 col-md-8">
                <div style="text-align:center; margin-top:25px;">
                    <div style="color:#A154A1; font-size:48px; font-weight:bold;">Love Our Way</div>
                    <div><img src="/imgs/logo.png" style="height:100px;"></div>
                    <div style="margin-top:20px;"><h3>Sharing Memories is Ageless</h3></div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-2 col-md-4"></div>
            <div class="col-lg-8 col-md-4">
                <div style="text-align:center; margin-top:25px">
                    <div class="form-group">
                        <input id="username" type="email" class="form-control" placeholder="Email address" required="">
                    </div>
                    <button id="btn_reset" class="btn btn-primary block full-width m-b">Reset your password</button>
                </div>
            </div>
        </div>

    </div>
    <div style="height:100px;"></div>
</div>
